# Generated by Django 4.1.6 on 2023-03-25 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='post',
            name='blog',
        ),
    ]
